[package]
name = "advent-of-code-2016"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "day01part1"
path = "src/day01/day01part1.rs"

[[bin]]
name = "day01part2"
path = "src/day01/day01part2.rs"

[[bin]]
name = "day02part1"
path = "src/day02/day02part1.rs"

[[bin]]
name = "day02part2"
path = "src/day02/day02part2.rs"

[[bin]]
name = "day03part1"
path = "src/day03/day03part1.rs"

[[bin]]
name = "day04part1"
path = "src/day04/day04part1.rs"

[[bin]]
name = "day04part2"
path = "src/day04/day04part2.rs"

[[bin]]
name = "day06part1"
path = "src/day06/day06part1.rs"

[[bin]]
name = "day06part2"
path = "src/day06/day06part2.rs"
